test = [
    "A paragraph is a self contained unit of multiple lines which have a real meaning.",
    "My name is Sarim and I am a good boy. I have a bike which I use for going to my college with my friend.",
    "Welcome to my flat." "Premises or poverty is one of the world’s most familiar concerns that impact millions of people and their households. It is also represented not only by limited funds, but by limited rights, for example, the right to education, healthcare, and housing. Most definitions of poverty explain it as a situation where an individual is denied some basic rights that enable her or him to lead a fulfilled life", "In addition, poverty results in poor social order and integration in the society, increases social vices such as crime and political instability and poor human health.","Tackling poverty is not simply the societal’s moral imperative; it is a precondition for economic development and social stability. Reducing poverty levels means that the rate of national production rises and everyone gains better health and a longer life. Therefore, poverty reduction is not only a crucial goal for people’s live standard but also for the country’s development." 

"As a project within this course, this work examines the mechanisms of legal responses to poverty including…the proper objectives of property, law against discrimination, social welfare legislations, and regulation. Thus, examining these aspects, we will try to contribute to understanding how efficient legal frameworks can support efforts in combating poverty and economic growth. This will involve exploring how and to what extent at least one legal element interacts with the others, and how this interactive influence Impacts poverty reduction measures."
"Poverty can be defined in two primary ways: absolute poverty and relative poverty? Absolute Poverty: This term points to a state in which persons cannot afford the necessities of life including food, pure water, shelter and clothing. Mostly, it refers to a situation where people cannot gain access to basic needs for the survival of life with dignity.", "This is often measured in terms of an income level, these includes world bank’s international poverty level set at 1.90 US dollars per day. Those below such poverty level are exposed to stringent poverty deprivations; higher incidences of diseases and early mortality due to poor dieting and poor nutrition." ,

"Relative Poverty: While relative poverty focuses on the comparison of an individual to that of the rest of society. It is the inadequacy of assets, or income to the level considered necessary to live a decent life within a given society for a given period. For example, in developed countries, people could be classified as poor as far as they receive considerably less than the average level of economic wealth, nevertheless, they are financially capable of supporting their necessities. Relative poverty therefore viewing poverty from the societal standards or perceptive of what constitutes poverty."



]